### ISSUE TITLE
Dimensions in model doesn't match the dimensions in the checkpoint

### ISSUE THREAD

**Issue by michaelzhang917** [metalbubble/TRN-pytorch#10]
I was trying to run the test_video.py and got the following error messages.

Traceback (most recent call last):
  File "test_video.py", line 104, in <module>
    img_feature_dim=args.img_feature_dim, print_spec=False)
  File "/home/vbalab/projects/SimpleMovementDetection/TRN-pytorch/models.py", line 43, in __init__
    self._prepare_base_model(base_model)
  File "/home/vbalab/projects/SimpleMovementDetection/TRN-pytorch/models.py", line 120, in _prepare_base_model
    self.base_model = getattr(model_zoo, base_model)()
  File "/home/vbalab/projects/SimpleMovementDetection/TRN-pytorch/model_zoo/bninception/pytorch_load.py", line 67, in __init__
    super(InceptionV3, self).__init__(model_path=model_path, weight_url=weight_url, num_classes=num_classes)
  File "/home/vbalab/projects/SimpleMovementDetection/TRN-pytorch/model_zoo/bninception/pytorch_load.py", line 35, in __init__
    self.load_state_dict(torch.utils.model_zoo.load_url(weight_url))
  File "/home/vbalab/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for InceptionV3:
	While copying the parameter named "conv_batchnorm.weight", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([1, 32]).
	While copying the parameter named "conv_batchnorm.bias", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([1, 32]).
	While copying the parameter named "conv_batchnorm.running_mean", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([1, 32]).
	While copying the parameter named "conv_batchnorm.running_var", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([1, 32]).
	While copying the parameter named "conv_1_batchnorm.weight", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([1, 32]).
	While copying the parameter named "conv_1_batchnorm.bias", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([1, 32]).
	While copying the parameter named "conv_1_batchnorm.running_mean", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([1, 32]).
	While copying the parameter named "conv_1_batchnorm.running_var", whose dimensions in the model are torch.Size([32]) and whose dimensions in the checkpoint are torch.Size([1, 32]).
	While copying the parameter named "conv_2_batchnorm.weight", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([1, 64]).
	While copying the parameter named "conv_2_batchnorm.bias", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([1, 64]).
	While copying the parameter named "conv_2_batchnorm.running_mean", whose dimensions in the model are torch.Size([64]) and whose dimensions in the checkpoint are torch.Size([1, 64]).
.......

**Comment by alexandonian** [comment]
Hi Yong Zhang,

I suspect that you are using the latest version of PyTorch (v0.4). Can you confirm this? We have encountered this same issue since upgrading. In the most recent commit (https://github.com/metalbubble/TRN-pytorch/commit/5005582e1b3acf3f901048052741df9b43bf3a4f), I have included links to download a new checkpoint file where these sizes of the batchnorm parameters have been corrected.

Unfortunately, this issue exists even in the base model checkpoint file. So even before you load the TRN pretrained model, the base BNInception/InceptionV3 checkpoints have this same issue. A quick fix for this is to simply comment out this line here:
https://github.com/yjxiong/tensorflow-model-zoo.torch/blob/e31e0b7aa451e2c12c0107e616953a03d8cd0d47/bninception/pytorch_load.py#L35

This prevents the original model weights from being loaded into the model. This is not an issue since you will soon after overwrite those weights with new ones from the TRN state_dict. Give this a shot and let me know if this helps. It seem to solve the issue on our end.

Best,
Alex A

**Comment by michaelzhang917** [comment]
It works with BNInception architecture but not InceptionV3

**Comment by zhangyuygss** [comment]
For those who would like to train the model, we can just squeeze out the extra dimension of the check point state_dict:
`
        state_dic = torch.utils.model_zoo.load_url(weight_url)
        for key in state_dic.keys():
            if '_bn' in key:
                state_dic[key] = state_dic[key].squeeze()

        self.load_state_dict(state_dic, strict=False)
`

**Comment by zhanwenchen** [comment]
I encountered the same problem across versions for my own model with `batch_norm`.

**Comment by kritiksoman** [comment]
I downloaded this 'http://data.lip6.fr/cadene/pretrainedmodels/bn_inception-52deb4733.pth' 
then replaced [https://github.com/yjxiong/tensorflow-model-zoo.torch/blob/e31e0b7aa451e2c12c0107e616953a03d8cd0d47/bninception/pytorch_load.py#L35](https://github.com/yjxiong/tensorflow-model-zoo.torch/blob/e31e0b7aa451e2c12c0107e616953a03d8cd0d47/bninception/pytorch_load.py#L35)
with
`        new_state_dict = {}
        temp2 = torch.load('model_zoo/bninception/bn_inception-52deb4733.pth')
        for k,v in temp2.items():
          if (k.split(".")[0]=='last_linear'):
            new_state_dict['fc.'+k.split(".")[1]] = v
          else:
            new_state_dict[k] = v        
         self.load_state_dict(new_state_dict, strict = False)`

**Comment by dralmadani** [comment]
> I downloaded this 'http://data.lip6.fr/cadene/pretrainedmodels/bn_inception-52deb4733.pth'
> then replaced https://github.com/yjxiong/tensorflow-model-zoo.torch/blob/e31e0b7aa451e2c12c0107e616953a03d8cd0d47/bninception/pytorch_load.py#L35
> with
> ` new_state_dict = {} temp2 = torch.load('model_zoo/bninception/bn_inception-52deb4733.pth') for k,v in temp2.items(): if (k.split(".")[0]=='last_linear'): new_state_dict['fc.'+k.split(".")[1]] = v else: new_state_dict[k] = v self.load_state_dict(new_state_dict, strict = False)`

Please, could you upload the data links again ?
