### ISSUE TITLE
Running TRN without CUDA

### ISSUE THREAD

**Issue by valeriechen** [metalbubble/TRN-pytorch#11]
Is there a workaround to this for running TRN on just cpu?

Valeries-MacBook-Pro:TRN-pytorch valeriechen$ python test_video.py --arch BNInception --dataset something     --weight pretrain/TRN_something_RGB_BNInception_TRNmultiscale_segment8_best.pth.tar     --frame_folder sample_data/bolei_juggling
Multi-Scale Temporal Relation Network Module in use ['8-frame relation', '7-frame relation', '6-frame relation', '5-frame relation', '4-frame relation', '3-frame relation', '2-frame relation']
Traceback (most recent call last):
  File "test_video.py", line 112, in <module>
    net.cuda().eval()
  File "/anaconda2/envs/mypython3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 216, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/anaconda2/envs/mypython3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/anaconda2/envs/mypython3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/anaconda2/envs/mypython3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 152, in _apply
    param.data = fn(param.data)
  File "/anaconda2/envs/mypython3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 216, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "/anaconda2/envs/mypython3/lib/python3.6/site-packages/torch/_utils.py", line 69, in _cuda
    return new_type(self.size()).copy_(self, async)
  File "/anaconda2/envs/mypython3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 384, in _lazy_new
    _lazy_init()
  File "/anaconda2/envs/mypython3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 141, in _lazy_init
    _check_driver()
  File "/anaconda2/envs/mypython3/lib/python3.6/site-packages/torch/cuda/__init__.py", line 55, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by valeriechen** [comment]
Just removed the .cuda()

**Comment by guruvishnuvardan** [comment]
Hi, is removing CUDA working??
