### ISSUE TITLE
test_video.py - AttributeError: 'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by crazyfrog-github** [metalbubble/TRN-pytorch#21]
Hi,

I tried to run on the pre-trained example and got the following error I am running on Windows 10, Anaconda, Python 3.6, Pytorch 0.3.0 etc, any idea why?:

(momentsintime) C:\Users\Pablo\TRN-pytorch>python test_video.py --arch InceptionV3 --dataset moments --weight pretrain\TRN_moments_RGB_InceptionV3_TRNmultiscale_segment8_best.pth.tar --video_file 'C:\Users\Pablo\TRN-pytorch\sample_data\bolei_juggling.mp4' --rendered_output 'C:\Users\Pablo\TRN-pytorch\sample_data\predicted_video.mp4'
Multi-Scale Temporal Relation Network Module in use ['8-frame relation', '7-frame relation', '6-frame relation', '5-frame relation', '4-frame relation', '3-frame relation', '2-frame relation']
Freezing BatchNorm2D except the first one.
Extracting frames using ffmpeg...
Traceback (most recent call last):
  File "test_video.py", line 133, in <module>
    frames = extract_frames(args.video_file, args.test_segments)
  File "test_video.py", line 33, in extract_frames
    duration = re_duration.search(str(output[1])).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by 595448755** [comment]
ubuntu18 have the same AttributeError,too.

**Comment by 595448755** [comment]
I run the same program successed ,
my computer is ubuntu18 + cuda 9.0 + cudnn 7.4.2 + python3.6 + torch 1.0

**Comment by azhaoaigaga** [comment]
Has this problem been solved？
