### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory at /pytorch

### ISSUE THREAD

**Issue by inspired27** [metalbubble/TRN-pytorch#22]
Hi,

I am trying to execute against example video or frame_folder both give the same error message any ideas:

ubuntu@ubuntu-pc:~/TRN-pytorch$ python3 test_video.py --arch BNInception --dataset something --weight pretrain/TRN_something_RGB_BNInception_TRNmultiscale_segment8_best.pth.tar --video_file sample_data/bolei_juggling.mp4
Multi-Scale Temporal Relation Network Module in use ['8-frame relation', '7-frame relation', '6-frame relation', '5-frame relation', '4-frame relation', '3-frame relation', '2-frame relation']
Freezing BatchNorm2D except the first one.
Extracting frames using ffmpeg...
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "test_video.py", line 140, in <module>
    logits = net(input_var)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/TRN-pytorch/models.py", line 220, in forward
    base_out = self.base_model(input.view((-1, sample_len) + input.size()[-2:]))
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/TRN-pytorch/model_zoo/bninception/pytorch_load.py", line 49, in forward
    data_dict[op[2]] = getattr(self, op[0])(data_dict[op[-1]])
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/batchnorm.py", line 37, in forward
    self.training, self.momentum, self.eps)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py", line 1013, in batch_norm
    return f(input, weight, bias)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58

**Comment by tdinzju** [comment]
I'm suffering from the same problem, Have you solved this problem?

**Comment by lianuo** [comment]
I'm suffering from the same problem,.....

**Comment by KAIIUK** [comment]
> I'm suffering from the same problem,.....
> 
> My GPU is GTX1080...8G is not enough?

do you fix this?

**Comment by adimukewar** [comment]
set batch size to 16.

**Comment by dineshp** [comment]
Following up on others, reduce batch size in training. For testing, since batch size is one, do the following:

change:

`transforms.GroupOverSample(net.input_size, net.scale_size),`

to

`    transforms.GroupScale(net.scale_size),
    transforms.GroupCenterCrop(net.input_size),`
