### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not int

### ISSUE THREAD

**Issue by anti1990** [metalbubble/TRN-pytorch#60]
Traceback (most recent call last):
  File "/home/ubuntu/TRN-pytorch/process_dataset.py", line 38, in <module>
    idx_categories.append(os.path.join(dict_categories[items[1]]))
  File "/home/ubuntu/anaconda3/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not int

I want to kmow how to solve this problem?

**Comment by Egoist1945** [comment]
> idx_categories.append(os.path.join(dict_categories[items[1]]))
changing this line to `idx_categories.append(dict_categories[items[1]])` may help

**Comment by Egoist1945** [comment]
> idx_categories.append(os.path.join(dict_categories[items[1]]))


changing this line to idx_categories.append(dict_categories[items[1]]) may help
