### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by azhaoaigaga** [metalbubble/TRN-pytorch#65]
python test_video.py --arch BNInception --dataset something --weights pretrain/TRN_something_RGB_BNInception_TRNmultiscale_segment8_best.pth.tar --fr
ame_folder E:\BaiduNetdiskDownload\TRN-pytorch\sample_data\sample_data\juggling_frames\
Test error：Traceback (most recent call last):
  File "test_video.py", line 137, in <module>
    logits = net(input)
  File "D:\Anaconda\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "E:\BaiduNetdiskDownload\TRN-pytorch\models.py", line 228, in forward
    base_out = base_out.view((-1, self.num_segments) + base_out.size()[1:])
RuntimeError: shape '[-1, 8, 256]' is invalid for input of size 15360

What Would l Do，thanks！

**Comment by YIYANGCAI** [comment]
Same problem, did you solve this problem?

**Comment by YamabukiKasumi** [comment]
Same problem, did you solve this problem?
